### ISSUE TITLE
draw関数のフレームレートについて

### ISSUE THREAD

**Issue by hirotta** [hina3ta/shinkan_2019#11]
https://github.com/hina3ta/shinkan_2019/blob/08114fd4af56f1e1c70106c3e1c0cd0a4489ed09/RccShooting/RccShooting.pde#L31
コードの変更ではないですが、
```
setup(){
…
frameRate(60);
…
}
```
が設定されてるので秒間60回の呼び出しじゃないかな？

**Comment by greenlaver** [comment]
享平の凡ミスです

**Comment by Yukiho-YOSHIEDA** [comment]
直します

**Comment by Yukiho-YOSHIEDA** [comment]
Closes #19

**Comment by Yukiho-YOSHIEDA** [comment]
Fixes #19

**Comment by hina3ta** [comment]
修正していただきました
