### ISSUE TITLE
レーザー弾幕を変更

### ISSUE THREAD

**Issue by Yukiho-YOSHIEDA** [hina3ta/shinkan_2019#16]
- こーだい先生によってぬるげになった
- 判定がガバイ

上記より変更する必要あり

**Comment by hina3ta** [comment]
変更箇所は違いますが、難易度を上げて調整しました。レーザーに関しては一つのものを何個か連ねてる感じのものになっています。

**Comment by hina3ta** [comment]
ビーム移動封じたから許してくださいなんでもし
