### ISSUE TITLE
当たり判定について

### ISSUE THREAD

**Issue by Yukiho-YOSHIEDA** [hina3ta/shinkan_2019#3]
shinkan_test#collision()にあると思いますが

- 判定は円でやっている？
- そうだとしたら実装がミスってそう

以上回答をお願いします

**Comment by hina3ta** [comment]
今gitにあがってる方を見てもらっていると思いますが、当たり判定は円ではありません。それぞれの物体のx, y, width, heightでとっています。引数が８こなのはこれが理由です。

**Comment by Yukiho-YOSHIEDA** [comment]
ということは四角で判定取ってる感じかな？
特に理由がない限り、円の判定のほうが実装しやすそうですが

**Comment by hina3ta** [comment]
わかりました
ロジック組みます

**Comment by Yukiho-YOSHIEDA** [comment]
円の当たり判定は
`物体間の距離 > 物体1の半径 + 物体2の半径`であれば当たっていなくて
そうじゃなければ当たっている
というロジックで大丈夫そう

**Comment by hina3ta** [comment]
わかりました

**Comment by Yukiho-YOSHIEDA** [comment]
fix #15

**Comment by Yukiho-YOSHIEDA** [comment]
closed #15
