### ISSUE TITLE
1回生に実装してもらう部分

### ISSUE THREAD

**Issue by Yukiho-YOSHIEDA** [hina3ta/shinkan_2019#4]
1回生ってどんなところを実装してもらう予定ですか？
上回生会議では実装しきってないからわからないと聞きましたが、設計するためにもある程度（「移動速度を変えてもらうつもり」や「弾幕を作成」）道筋がほしいです。
それによって、実装を隠す部分と見せる部分が変わってくるはずです。

**Comment by hina3ta** [comment]
今の所
・自機を動かす
・打つ弾
・弾に当たると死ぬようにする
・雑魚の配置の増加
辺かなと考えています。

**Comment by Yukiho-YOSHIEDA** [comment]
了解です
以下、議論パートです

## 自機を動かすについて
- 初期では動かせないようにしておいて動かせるようにする？
- キーを一度押したときの移動量を変更してもらう？
## 打つたまについて
- 画像を変更してもらう？
- 連射機能をつけてもらう？
- 軌道（一度に3つ出たり）を変えてもらう？
## 弾にあたると死ぬについて
- 自機？敵機？
- HPはある？
## 雑魚の配置の増加について
- 位置は指定する？

ここまで具体的にすると実装しやすそう
（時間の兼ね合いもあるので取捨選択してください）

**Comment by hina3ta** [comment]
<h2>自機を動かすについて</h2>
初期では動かせないようにしておいて動かせるようにする
<h2>打つたまについて</h2>
最初は打てなくして、打てるようにしてもらう
<h2>弾にあたると死ぬについて</h2>
自機に限定
HPはある
最初は表示中のHPがマイナスになっても稼働する -> gameoverを表示
<h2>雑魚の配置の増加について</h2>
追加する位置はすでに作ったものを使う

**Comment by hina3ta** [comment]
上記で決定しました
