### ISSUE TITLE
不要ファイルの削除

### ISSUE THREAD

**Issue by greenlaver** [hina3ta/shinkan_2019#6]
## 教材として不要なファイルの削除
以下のファイルは、教材として不要（或いは見えない方がいい）ファイルなので、
ある程度実装が終わった後削除すべきです。

- [nya-n.txt](https://github.com/hina3ta/shinkan_2019/blob/cfe4c5458ae958b023ee4f329d1d95d6a2f89355/nya-n.txt)
- [新歓二次企画について.docx](https://github.com/hina3ta/shinkan_2019/blob/cfe4c5458ae958b023ee4f329d1d95d6a2f89355/RccShooting/%E6%96%B0%E6%AD%93%E4%BA%8C%E6%AC%A1%E4%BC%81%E7%94%BB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6.docx)

**Comment by hina3ta** [comment]
大丈夫です！
明日には消しておきます！

**Comment by hina3ta** [comment]
消しました
